project_id = "olvsadoyrfwsbhacqteg"

[functions.medication-info]
verify_jwt = false

[functions.medication-interactions]
verify_jwt = false

[functions.medication-dosage]
verify_jwt = false

[functions.search-medications]
verify_jwt = false

[functions.travel-recommendations]
verify_jwt = false

[functions.search-countries]
verify_jwt = false
